export const actionTypes = {
  // animals
  LOAD_ANIMALS: 'LOAD_ANIMALS',
  LOAD_ANIMALS_SUCCESS: 'LOAD_ANIMALS_SUCCESS',
  LOAD_ANIMALS_FAILURE: 'LOAD_ANIMALS_FAILURE',

  // food
  LOAD_FOOD: 'LOAD_FOOD',
  LOAD_FOOD_SUCCESS: 'LOAD_FOOD_SUCCESS',
  LOAD_FOOD_FAILURE: 'LOAD_FOOD_FAILURE'
}